site_name: Вики Кошкокрафта
site_author: Всекотец
site_url: https://wiki.catcraftmc.ru/

repo_url: https://github.com/szarkans/szarkans.github.io
repo_name: Вики КК
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil   
  language: ru
  features:
    - content.tabs.link
 #   - navigation.instant
  #  - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
   # - navigation.prune
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.action.edit
  logo: assets/icon.png
  favicon: assets/icon.png
  font:
    text: Inter
    code: Fira Code
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - pymdownx.critic
  - pymdownx.snippets:
      auto_append:
        - includes/links.md
  - toc:
      permalink: "#"
      separator: "_"
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - def_list
  - md_in_html
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
  - stylesheets/my.css
  - stylesheets/admonitions.css
plugins:
  - search
  - open-in-new-tab
  - minify:
      minify_html: true
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
 # - javascripts/players.js
  - javascripts/effects.js
  - javascripts/img_expand.js
extra: 
  consent:
    title: Одобри печеньки!
    description:
      Мы используем твои куки для просмотра аналитики нашей Вики (кто, что, где, какую страницу смотрят чаще и т.п.)
  status:
    new: Новое!
    inprogress: Статья не завершена
  analytics: 
    provider: google
    property: G-X3KCR2ZW65
  social:
    - icon: simple/vk
      link: https://vk.com/catcraftmc
      name: Наш ВК
    - icon: simple/discord
      link: https://discord.gg/23XJyDGJaH
      name: Наш Дискорд
    - icon: material/map
      link: https://vk.cc/ct7HsI
      name: Наша Карта
nav:
  - ' ': index.md
  - Информация:
    - info/admins.md
    # - info/dict.md
    # - info/faq.md
    # - info/donate.md
    # - info/guide.md
    # - info/map.md
    # - info/for_media.md
    - 'Правила и законы':
      - info/rules/rules.md
      - info/rules/laws.md
    - 'Моды':
      - info/mods/mods.md
      - info/mods/required_mods.md
      - info/mods/cool_mods.md
  # - Геймплей:
  #   - Роллплей:
  #     - gameplay/roleplay/goverment.md
  #     - gameplay/roleplay/police.md
  #   - Уникальные фишки:
  #     - gameplay/unique/qol.md
  #     - gameplay/unique/resourcepack.md
  #     - gameplay/unique/npc.md
  #     - gameplay/unique/villager_rebalance.md
  #     - gameplay/unique/datapacks.md
  #     - gameplay/unique/artmap.md
  #     - gameplay/unique/clans.md
  #     - gameplay/unique/armorstand.md
  #     - gameplay/unique/wandering_trader.md
  #     - gameplay/unique/prefixes.md
  #     - Кастомные модели персонажа:
  #       - gameplay/unique/cpm/index.md
  #       - gameplay/unique/cpm/cpm_guide.md
  #     - "gameplay/unique/brewery.md"
  #     - Рыбалка:
  #       - "gameplay/unique/fishing/index.md"
  #       - Список рыб: gameplay/unique/fishing/fish_list.md
  #     - gameplay/unique/voicechat.md
  #   - Награды игрокам:
  #     - gameplay/rewards/list.md
  #     - gameplay/rewards/catpass.md
  #   - Команды:
  #     - gameplay/commands/ingame.md
  #     - gameplay/commands/discord.md
  # - Предметы:
  #   - Накладываемое:
  #     - "items/clickable/cattrack.md"
  #     - "items/clickable/scroll.md"
  #   - Блоки:
  #     - "items/blocks/gycha.md"
  #     - "items/blocks/compressed.md"
  #     - "items/blocks/reinforced.md"
  #     - "items/blocks/light.md"
  #     - "items/blocks/invis_frame.md"
  #   - Применяемое:
  #     - "items/usable/kplus.md"
  #   - Кастомные предметы:
  #     - "items/custom_items/gh.md"
  #     - "items/custom_items/plushie.md"
  #     - "items/custom_items/kotomat.md"
  #     - "items/custom_items/holy_books.md"
  #   - Ванильные предметы:
  #     - "items/vanilla/templates.md"
  #     - "items/vanilla/totem.md"
  - Гайды:
    - Игровое:
      - guides/set_skin.md
      - guides/rgb_nick.md
    - Техническое:
      - guides/mod_download.md
      - guides/mod_errors.md
      - guides/skins_tlauncher.md
    - Разное:
      - guides/launcher.md
      - guides/edit_wiki.md
  - История сервера:
    - server-history/1season.md
    - server-history/2season.md
    - server-history/3season.md
    - server-history/4season.md
    - server-history/5season.md
